/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VanRouteImport } from './routes/van'
import { Route as StockCountRouteImport } from './routes/stock-count'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SalesDepositsRouteImport } from './routes/sales-deposits'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReconciliationRouteImport } from './routes/reconciliation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PosRouteImport } from './routes/pos'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HealthRouteImport } from './routes/health'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FarmersRouteImport } from './routes/farmers'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CustomerFeedbackRouteImport } from './routes/customer-feedback'
import { Route as CollectionPointsRouteImport } from './routes/collection-points'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as R500RouteImport } from './routes/500'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyIdRouteImport } from './routes/verify/$id'
import { Route as ReceiptIdRouteImport } from './routes/receipt/$id'
import { Route as InvoiceIdRouteImport } from './routes/invoice/$id'
import { Route as StatementFarmerIdRouteImport } from './routes/statement/farmer.$id'
import { Route as StatementCustomerIdRouteImport } from './routes/statement/customer.$id'
import { Route as ReportDayCloseDateRouteImport } from './routes/report/day-close.$date'
import { Route as ReceiptDepositIdRouteImport } from './routes/receipt/deposit.$id'
import { Route as PayoutFarmerIdRouteImport } from './routes/payout/farmer.$id'
import { Route as PaymentsFarmerIdRouteImport } from './routes/payments/farmer.$id'

const VanRoute = VanRouteImport.update({
  id: '/van',
  path: '/van',
  getParentRoute: () => rootRouteImport,
} as any)
const StockCountRoute = StockCountRouteImport.update({
  id: '/stock-count',
  path: '/stock-count',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDepositsRoute = SalesDepositsRouteImport.update({
  id: '/sales-deposits',
  path: '/sales-deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReconciliationRoute = ReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmersRoute = FarmersRouteImport.update({
  id: '/farmers',
  path: '/farmers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerFeedbackRoute = CustomerFeedbackRouteImport.update({
  id: '/customer-feedback',
  path: '/customer-feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionPointsRoute = CollectionPointsRouteImport.update({
  id: '/collection-points',
  path: '/collection-points',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyIdRoute = VerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementFarmerIdRoute = StatementFarmerIdRouteImport.update({
  id: '/statement/farmer/$id',
  path: '/statement/farmer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementCustomerIdRoute = StatementCustomerIdRouteImport.update({
  id: '/statement/customer/$id',
  path: '/statement/customer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportDayCloseDateRoute = ReportDayCloseDateRouteImport.update({
  id: '/report/day-close/$date',
  path: '/report/day-close/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptDepositIdRoute = ReceiptDepositIdRouteImport.update({
  id: '/receipt/deposit/$id',
  path: '/receipt/deposit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutFarmerIdRoute = PayoutFarmerIdRouteImport.update({
  id: '/payout/farmer/$id',
  path: '/payout/farmer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFarmerIdRoute = PaymentsFarmerIdRouteImport.update({
  id: '/payments/farmer/$id',
  path: '/payments/farmer/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/catalog': typeof CatalogRoute
  '/collection-points': typeof CollectionPointsRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/farmers': typeof FarmersRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/pos': typeof PosRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/sales-deposits': typeof SalesDepositsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/stock': typeof StockRoute
  '/stock-count': typeof StockCountRoute
  '/van': typeof VanRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/payments/farmer/$id': typeof PaymentsFarmerIdRoute
  '/payout/farmer/$id': typeof PayoutFarmerIdRoute
  '/receipt/deposit/$id': typeof ReceiptDepositIdRoute
  '/report/day-close/$date': typeof ReportDayCloseDateRoute
  '/statement/customer/$id': typeof StatementCustomerIdRoute
  '/statement/farmer/$id': typeof StatementFarmerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/catalog': typeof CatalogRoute
  '/collection-points': typeof CollectionPointsRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/farmers': typeof FarmersRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/pos': typeof PosRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/sales-deposits': typeof SalesDepositsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/stock': typeof StockRoute
  '/stock-count': typeof StockCountRoute
  '/van': typeof VanRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/payments/farmer/$id': typeof PaymentsFarmerIdRoute
  '/payout/farmer/$id': typeof PayoutFarmerIdRoute
  '/receipt/deposit/$id': typeof ReceiptDepositIdRoute
  '/report/day-close/$date': typeof ReportDayCloseDateRoute
  '/statement/customer/$id': typeof StatementCustomerIdRoute
  '/statement/farmer/$id': typeof StatementFarmerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/500': typeof R500Route
  '/catalog': typeof CatalogRoute
  '/collection-points': typeof CollectionPointsRoute
  '/customer-feedback': typeof CustomerFeedbackRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/expenses': typeof ExpensesRoute
  '/farmers': typeof FarmersRoute
  '/feedback': typeof FeedbackRoute
  '/finance': typeof FinanceRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/offline': typeof OfflineRoute
  '/pos': typeof PosRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reconciliation': typeof ReconciliationRoute
  '/reports': typeof ReportsRoute
  '/sales-deposits': typeof SalesDepositsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/stock': typeof StockRoute
  '/stock-count': typeof StockCountRoute
  '/van': typeof VanRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/receipt/$id': typeof ReceiptIdRoute
  '/verify/$id': typeof VerifyIdRoute
  '/payments/farmer/$id': typeof PaymentsFarmerIdRoute
  '/payout/farmer/$id': typeof PayoutFarmerIdRoute
  '/receipt/deposit/$id': typeof ReceiptDepositIdRoute
  '/report/day-close/$date': typeof ReportDayCloseDateRoute
  '/statement/customer/$id': typeof StatementCustomerIdRoute
  '/statement/farmer/$id': typeof StatementFarmerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/500'
    | '/catalog'
    | '/collection-points'
    | '/customer-feedback'
    | '/customers'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/farmers'
    | '/feedback'
    | '/finance'
    | '/health'
    | '/help'
    | '/maintenance'
    | '/offline'
    | '/pos'
    | '/production'
    | '/products'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/sales-deposits'
    | '/search'
    | '/settings'
    | '/status'
    | '/stock'
    | '/stock-count'
    | '/van'
    | '/invoice/$id'
    | '/receipt/$id'
    | '/verify/$id'
    | '/payments/farmer/$id'
    | '/payout/farmer/$id'
    | '/receipt/deposit/$id'
    | '/report/day-close/$date'
    | '/statement/customer/$id'
    | '/statement/farmer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/500'
    | '/catalog'
    | '/collection-points'
    | '/customer-feedback'
    | '/customers'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/farmers'
    | '/feedback'
    | '/finance'
    | '/health'
    | '/help'
    | '/maintenance'
    | '/offline'
    | '/pos'
    | '/production'
    | '/products'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/sales-deposits'
    | '/search'
    | '/settings'
    | '/status'
    | '/stock'
    | '/stock-count'
    | '/van'
    | '/invoice/$id'
    | '/receipt/$id'
    | '/verify/$id'
    | '/payments/farmer/$id'
    | '/payout/farmer/$id'
    | '/receipt/deposit/$id'
    | '/report/day-close/$date'
    | '/statement/customer/$id'
    | '/statement/farmer/$id'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/500'
    | '/catalog'
    | '/collection-points'
    | '/customer-feedback'
    | '/customers'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/farmers'
    | '/feedback'
    | '/finance'
    | '/health'
    | '/help'
    | '/maintenance'
    | '/offline'
    | '/pos'
    | '/production'
    | '/products'
    | '/profile'
    | '/reconciliation'
    | '/reports'
    | '/sales-deposits'
    | '/search'
    | '/settings'
    | '/status'
    | '/stock'
    | '/stock-count'
    | '/van'
    | '/invoice/$id'
    | '/receipt/$id'
    | '/verify/$id'
    | '/payments/farmer/$id'
    | '/payout/farmer/$id'
    | '/receipt/deposit/$id'
    | '/report/day-close/$date'
    | '/statement/customer/$id'
    | '/statement/farmer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R500Route: typeof R500Route
  CatalogRoute: typeof CatalogRoute
  CollectionPointsRoute: typeof CollectionPointsRoute
  CustomerFeedbackRoute: typeof CustomerFeedbackRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  DriversRoute: typeof DriversRoute
  ExpensesRoute: typeof ExpensesRoute
  FarmersRoute: typeof FarmersRoute
  FeedbackRoute: typeof FeedbackRoute
  FinanceRoute: typeof FinanceRoute
  HealthRoute: typeof HealthRoute
  HelpRoute: typeof HelpRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OfflineRoute: typeof OfflineRoute
  PosRoute: typeof PosRoute
  ProductionRoute: typeof ProductionRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ReconciliationRoute: typeof ReconciliationRoute
  ReportsRoute: typeof ReportsRoute
  SalesDepositsRoute: typeof SalesDepositsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  StockRoute: typeof StockRoute
  StockCountRoute: typeof StockCountRoute
  VanRoute: typeof VanRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
  VerifyIdRoute: typeof VerifyIdRoute
  PaymentsFarmerIdRoute: typeof PaymentsFarmerIdRoute
  PayoutFarmerIdRoute: typeof PayoutFarmerIdRoute
  ReceiptDepositIdRoute: typeof ReceiptDepositIdRoute
  ReportDayCloseDateRoute: typeof ReportDayCloseDateRoute
  StatementCustomerIdRoute: typeof StatementCustomerIdRoute
  StatementFarmerIdRoute: typeof StatementFarmerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/van': {
      id: '/van'
      path: '/van'
      fullPath: '/van'
      preLoaderRoute: typeof VanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-count': {
      id: '/stock-count'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof StockCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-deposits': {
      id: '/sales-deposits'
      path: '/sales-deposits'
      fullPath: '/sales-deposits'
      preLoaderRoute: typeof SalesDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reconciliation': {
      id: '/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof ReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmers': {
      id: '/farmers'
      path: '/farmers'
      fullPath: '/farmers'
      preLoaderRoute: typeof FarmersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-feedback': {
      id: '/customer-feedback'
      path: '/customer-feedback'
      fullPath: '/customer-feedback'
      preLoaderRoute: typeof CustomerFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection-points': {
      id: '/collection-points'
      path: '/collection-points'
      fullPath: '/collection-points'
      preLoaderRoute: typeof CollectionPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$id': {
      id: '/verify/$id'
      path: '/verify/$id'
      fullPath: '/verify/$id'
      preLoaderRoute: typeof VerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement/farmer/$id': {
      id: '/statement/farmer/$id'
      path: '/statement/farmer/$id'
      fullPath: '/statement/farmer/$id'
      preLoaderRoute: typeof StatementFarmerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statement/customer/$id': {
      id: '/statement/customer/$id'
      path: '/statement/customer/$id'
      fullPath: '/statement/customer/$id'
      preLoaderRoute: typeof StatementCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/day-close/$date': {
      id: '/report/day-close/$date'
      path: '/report/day-close/$date'
      fullPath: '/report/day-close/$date'
      preLoaderRoute: typeof ReportDayCloseDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/deposit/$id': {
      id: '/receipt/deposit/$id'
      path: '/receipt/deposit/$id'
      fullPath: '/receipt/deposit/$id'
      preLoaderRoute: typeof ReceiptDepositIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payout/farmer/$id': {
      id: '/payout/farmer/$id'
      path: '/payout/farmer/$id'
      fullPath: '/payout/farmer/$id'
      preLoaderRoute: typeof PayoutFarmerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/farmer/$id': {
      id: '/payments/farmer/$id'
      path: '/payments/farmer/$id'
      fullPath: '/payments/farmer/$id'
      preLoaderRoute: typeof PaymentsFarmerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R500Route: R500Route,
  CatalogRoute: CatalogRoute,
  CollectionPointsRoute: CollectionPointsRoute,
  CustomerFeedbackRoute: CustomerFeedbackRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  DriversRoute: DriversRoute,
  ExpensesRoute: ExpensesRoute,
  FarmersRoute: FarmersRoute,
  FeedbackRoute: FeedbackRoute,
  FinanceRoute: FinanceRoute,
  HealthRoute: HealthRoute,
  HelpRoute: HelpRoute,
  MaintenanceRoute: MaintenanceRoute,
  OfflineRoute: OfflineRoute,
  PosRoute: PosRoute,
  ProductionRoute: ProductionRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ReconciliationRoute: ReconciliationRoute,
  ReportsRoute: ReportsRoute,
  SalesDepositsRoute: SalesDepositsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  StockRoute: StockRoute,
  StockCountRoute: StockCountRoute,
  VanRoute: VanRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  ReceiptIdRoute: ReceiptIdRoute,
  VerifyIdRoute: VerifyIdRoute,
  PaymentsFarmerIdRoute: PaymentsFarmerIdRoute,
  PayoutFarmerIdRoute: PayoutFarmerIdRoute,
  ReceiptDepositIdRoute: ReceiptDepositIdRoute,
  ReportDayCloseDateRoute: ReportDayCloseDateRoute,
  StatementCustomerIdRoute: StatementCustomerIdRoute,
  StatementFarmerIdRoute: StatementFarmerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
