-- African Joy Dairy POS
-- 00032: bulk import of existing customer names from the paper ledger.
-- Names only, no phone/email/type given, so every one lands as type
-- 'cash' (the same default the Add customer form itself uses) with
-- everything else on its normal default. Staff can edit any of them
-- individually afterward (phone, switch to credit/monthly, etc.).

insert into public.customers (name, type) values
  ('BAYANA', 'cash'),
  ('Judith', 'cash'),
  ('Juma', 'cash'),
  ('Kelvin', 'cash'),
  ('Rehana', 'cash'),
  ('Ketan Patel', 'cash'),
  ('Vicki', 'cash'),
  ('PRAYS', 'cash'),
  ('Madam Joy', 'cash'),
  ('Waziri', 'cash'),
  ('MAMI''S BISTRO', 'cash'),
  ('VALONIA APPARTMENT', 'cash'),
  ('MAMA SAMBA', 'cash'),
  ('MAMA DESUZA', 'cash'),
  ('Mama Crater', 'cash'),
  ('Mama Esther', 'cash'),
  ('MAMA MTENGA', 'cash'),
  ('Laura', 'cash'),
  ('Mawala', 'cash'),
  ('SIDHU', 'cash'),
  ('MAMA MATUNGA', 'cash'),
  ('KIDEVU', 'cash'),
  ('BOB', 'cash'),
  ('MAMA LAKI', 'cash'),
  ('MAMA MALAKAI', 'cash'),
  ('MAMA JOSHUA', 'cash'),
  ('Judy', 'cash'),
  ('Betty', 'cash'),
  ('VICKY PAROKIA', 'cash'),
  ('TAMARA', 'cash'),
  ('EZEKIELI', 'cash'),
  ('Sarah Goroi', 'cash'),
  ('Erick', 'cash'),
  ('KIWANDANI', 'cash'),
  ('NYUMBANI', 'cash'),
  ('IRENE RANONIS', 'cash'),
  ('BIBI MADAM', 'cash'),
  ('BIBI OLKERIAN', 'cash'),
  ('BABU', 'cash'),
  ('KIVUYO', 'cash'),
  ('MAMA NOBLE', 'cash'),
  ('BAKITA ,MAPADRI', 'cash'),
  ('HAKIMU', 'cash'),
  ('JOVINARY', 'cash'),
  ('MRS JOVINARY', 'cash'),
  ('NELLY', 'cash'),
  ('MAMA NAELI', 'cash'),
  ('WALTER', 'cash'),
  ('MAMA HUSSEIN', 'cash'),
  ('HAIKA BOSCO', 'cash'),
  ('CROTIDA', 'cash'),
  ('MOUNT MERU', 'cash'),
  ('RASHDA', 'cash'),
  ('CAPTOLINA', 'cash');
